### ISSUE TITLE
Ülesanne 5

### ISSUE THREAD

**Issue by elsaneth** [Papilegend/Ryhm-E#30]
# Ülesanne 5 - Write a function

## Kirjeldus

An extra day is added to the calendar almost every four years as February 29, and the day is called a leap day. It corrects the calendar for the fact that our planet takes approximately 365.25 days to orbit the sun. A leap year contains a leap day.

In the Gregorian calendar, three conditions are used to identify leap years:

The year can be evenly divided by 4, is a leap year, unless:
The year can be evenly divided by 100, it is NOT a leap year, unless:
The year is also evenly divisible by 400. Then it is a leap year.
This means that in the Gregorian calendar, the years 2000 and 2400 are leap years, while 1800, 1900, 2100, 2200, 2300 and 2500 are NOT leap years. [Source](http://www.timeanddate.com/date/leapyear.html)

**Task**

Given a year, determine whether it is a leap year. If it is a leap year, return the Boolean True, otherwise return False.

Note that the code stub provided reads from STDIN and passes arguments to the is_leap function. It is only necessary to complete the is_leap function.

**Input Format**

Read , the year to test.

**Output Format**

The function must return a Boolean value (True/False). Output is handled by the provided code stub.

## Muudatuse tüüp

- [x] Uus funktsioon
- [x] Vea parandus

## Kuidas on see testitud?

kasutades HackerRanki automaatteste

![Image](https://user-images.githubusercontent.com/119224484/220959720-8ac6bed0-b12f-49d5-a00a-60935983db56.PNG)

## Kasutatud keel:

Python

## Kontroll-nimekiri
- [x] Kood järgib selle projekti stiiliga seotud reegleid
- [x] Kood on selge ja loetav
- [x] Kood on vastavalt vajadusele kommenteeritud
- [x] Ma olen teinud vastavad muudatused dokumentatsioonis
- [x] Ülesande automaattestid läbisid (automaattestid on lehel olemas)
- [x] Ma olen lisanud testid, mis tõestavad minu paranduse tõhusust või
uue funktsionaalsuse toimimist
- [x] Kasutatavad välised teegid on lisatud
